cc_binary(
    name = "gate_svr",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//thirdparty/tinyxml:tinyxml",
        "//common/network:network",
        "#pthread",
        "#boost_system",
        "//common/logger:logger",
    ],
    incs = [
        "../../thirdparty/tinyxml",
        "../../common/network",
        "../../common/logger",
        "../../thirdparty/glog-0.3.3",
    ],
)
