cc_binary(
    name = "gate_svr",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//thirdparty/tinyxml:tinyxml",
        "//common/network:network",
        "#pthread",
        "#boost_system",
    ],
    incs = [
        "//thirdparty/tinyxml",
        "//common/network",
    ],
)
