cc_library(
    name = "network",
    srcs = [
        "TcpClient.cpp",
        "TcpConnection.cpp",
        "TcpServer.cpp",
    ],
    deps = [
    ],
    incs = [
        ".",
        "../logger",
        "../../thirdparty/glog-0.3.3",
    ],
)
